const SCREENS = {
  ACCOUNT: 'Account',
  CHANGE_PASSWORD: 'ChangePassword',
  PERSONAL_INFORMATION: 'PersonalInformation',
  LIST_POST: 'ListPosts',
  CONFIRM_POST_SCREEN: 'ConfirmPostScreen',
  CREATE_POST: 'CreatePost',
  MAPS: 'MapScreen',
  DRAFT_POSTS: 'DraftPosts',
  USER_POSTS: 'UserPosts',
  UPGRADE_ACCOUNT_SCREEN: 'UpgradeAccountScreen',
  GENERAL_INFORMATION_SCREEN: 'GeneralInformationScreen',
  LIST_STAFF_SCREEN: 'ListStaffScreen',
  UPGRADE_ACCOUNT_TAB: 'UpgradeAccountTab',
  AGENCY_INFORMATION_TAB: 'AgencyInformationTab',
  LIST_PROJECT: 'ListProject',
  INDIVIDUAL_FEATURE_SCREEN: 'IndividualFeatureScreen',
  NOTES_SCREEN: 'NotesScreen',
  HISTORY: 'History',
  HOME: 'Home',
  LIST_POSTS: 'ListPosts',
  MANAGE_POSTS: 'ManagePost',
  WAREHOUSELAND: 'WareHouseLand',
  FILTER_SCREEN: 'FilterScreen',
  DEPOSIT_SCREEN: 'DepositScreen',
  PERSONAL_PAGE_SCREEN: 'PersonalPageScreen',
  DETAIL_POST: 'DetailPost',
  COLLABORATOR_SCREEN: 'CollaboratorInformationScreen',
  ADD_ACCOUNT_SCREEN: 'AddAccountScreen',
  CHANGE_STATUS_SCREEN: 'ChangeStatusScreen',
  STAFF_INFORMATION_SCREEN: 'StaffInformationScreen',
  REQUEST_CONTACT_SCREEN: 'RequestContactScreen',
  USERAPPOINMENTSCREEN: 'UserAppoinmentScreen',
  CREATEAPPOIONMENTSCREEN: 'CreatetAppoinmentScreen',
  BUY_PACKAGE: 'BuyPackage',
};

export default SCREENS;
